name: Bug report
description: Report a problem with this project
title: '[bug]: '
labels: ['bug']
body:
    - type: textarea
      id: bug
      attributes:
          label: Describe the bug
          description: Describe the bug you encountered concisely.
      validations:
          required: true
    - type: textarea
      id: reproduction
      attributes:
          label: Steps to reproduce
          description: Describe the steps to reproduce the bug.
          placeholder: |
              1. Do this
              2. Do that
              3. Encounter bug
      validations:
          required: true
    - type: textarea
      id: expected
      attributes:
          label: Expected behavior
          description: Describe the behavior you expected.
      validations:
          required: true
    - type: textarea
      id: additional
      attributes:
          label: Additional information
          description: Provide screenshots, code snippets, error logs, or any other additional information to assist in debugging.
      validations:
          required: false
    - type: input
      id: os
      attributes:
          label: Operating system
          description: What operating system did you encounter the bug on?
      validations:
          required: true
