name: Feature request
description: Suggest an idea for this project
title: '[feat]: '
labels: ['enhancement']
body:
    - type: textarea
      id: feature
      attributes:
          label: Proposed feature
          description: Please describe what this feature solves or improves. What is the desired functionality this feature will provide?
          placeholder: Describe feature here...
      validations:
          required: true
